#!/bin/bash

### BEGIN INIT INFO
# Provides:          catchmail
# Required-Start:    $remote_fs $syslog
# Required-Stop:     $remote_fs $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Short-Description: Start daemon at boot time
# Description:       Enable service provided by daemon.
### END INIT INFO

USER="vagrant"
PROCESS="mailcatcher"
COMMAND="/usr/local/bin/mailcatcher --http-ip 0.0.0.0"
RETVAL=0

case "$1" in
    
    start)
        sudo -u $USER $COMMAND
        RETVAL=$?
        ;;
    
    stop)
        sudo -u $USER killall -9 $PROCESS
        RETVAL=$?
        ;;
    
    restart)
        sudo -u $USER killall -9 $PROCESS
        sudo -u $USER $COMMAND
        RETVAL=$?
        ;;

    status)
        sudo -u $USER ps -e | grep $PROCESS
        RETVAL=$?
        ;;
    
    *)
        echo "Usage: catchmail {start|stop|restart|status}"
        exit 1
        ;;
esac

exit $RETVAL